package edu.uchicago.mhmcdonald;

import edu.uchicago.mhmcdonald.domain.Episode;
import edu.uchicago.mhmcdonald.domain.Season;
import edu.uchicago.mhmcdonald.repository.EpisodeRepository;
import edu.uchicago.mhmcdonald.repository.SeasonRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.Arrays;


//Implementation of the Spring Boot Appliaction
@SpringBootApplication
public class ProWebserviceApplication implements CommandLineRunner {

    @Autowired
    private SeasonRepository seasonRepository;

    @Autowired
    private EpisodeRepository episodeRepository;

    public static void main(String[] args) {
        SpringApplication.run(ProWebserviceApplication.class, args);
    }

    //there are 7 seasons of the TV Show, "Parts Unkown"
    @Override
    public void run(String... strings) throws Exception {
        Season[] seasons = new Season[7];
        seasons[0] = new Season(1, "Season 1");
        seasons[1] = new Season(2, "Season 2");
        seasons[2] = new Season(3, "Season 3");
        seasons[3] = new Season(4, "Season 4");
        seasons[4] = new Season(5, "Season 5");
        seasons[5] = new Season(6, "Season 6");
        seasons[6] = new Season(7, "Season 7");


        seasonRepository.save(Arrays.asList(seasons));
        //this data was retrieved from the guidebox.com API. It adds these records to the H2 Database
        Episode[] episodes = new Episode[56];
        episodes[0] = new Episode("Bourdain looks at the Congo as one of the more industrialized powers in Africa now largely crumbled to nothingness and chaos with Tim Butcher author of Blood River.", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-8-1-1370761200-1054908778-large-400x225.jpg", 8, "Congo");
        episodes[1] = new Episode("Few cities have experienced such a dramatic economic rise and fall of Detroit. In this episode of Parts Unknown, Bourdain explores the past, present and future of the Motor City. He steps into the lives of Detroit natives and sees the glory days of the past at the famed Packard Plant, the current state of the city's urban decay, and the promise of the future in the citizens who are rebuilding their communities.", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-8-2-1384070400-9384480598-large-400x225.jpg", 8, "Detroit");
        episodes[2] = new Episode("Parts Unknown takes a close look at the mash-up of cultures that comprise this uniquely American state by sampling its food – a combination of Spanish, Mediterranean, Mexican, Pueblo and even chuck-wagon influences. New Mexico is also a land of drugs, guns, monster vehicles, and possibly extraterrestrials. It may also be the perfect place to investigate the underside of the Western cowboy ideal.", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-3-2-1380438000-5576674333-large-400x225.jpg", 3, "New Mexico");
        episodes[3] = new Episode("In the Season 3 premiere of Anthony Bourdain Parts Unknown Tony explores Punjab -- one of the most beautiful and relatively unknown areas of India. Punjab is the Sikh Holy Land and is also India's agricultural breadbasket.", seasons[2], "http://static-api.guidebox.com/thumbs03_14/thumbnails_episodes/15696-1-3-1397372400-1010416160-large-400x225.jpg", 1, "Punjab");
        episodes[4] = new Episode("Bourdain and his crew head to the Chiang Mai province of Northern Thailand along with celebrated chef and Thai food specialist Andy Ricker (Pok Pok restaurants) to explore the country's distinctive eating and drinking scene that varies by region and season.", seasons[2], "http://static-api.guidebox.com/041014/thumbnails_episodes/15696-7-3-1401606000-5346590746-large-400x225.jpg", 7, "Thailand");
        episodes[5] = new Episode(" Anthony Bourdain: Parts Unknown- A look back at the best of season 4 plus a sneak peak of season 5. ", seasons[0], "http://static-api.guidebox.com/misc/episode/default_400x225.jpg", 0, " Prime Cuts 4 ");
        episodes[6] = new Episode(" Anthony Bourdain: Prime Cuts- Season Two- A one-hour program hosted by Bourdain that takes a look back at the previous season featuring recaps, outtakes and commentary. ", seasons[0], "http://static-api.guidebox.com/misc/episode/default_400x225.jpg", 0, " Prime Cuts- Season 2 ");
        episodes[7] = new Episode(" In this food-centric episode, Bourdain accompanies world-renowned chef/restaurateur Daniel Boulud as they travel back to Boulud's hometown of Lyon, France for a 'once-in-a-lifetime' pilgrimage to the city's rich food culture and legendary chefs, with a focus on Nouvelle Cuisine innovator Paul Bocuse. ", seasons[3], "http://static-api.guidebox.com/thumbs03_14/thumbnails_episodes/15696-3-3-1398582000-4422966810-large-400x225.jpg", 3, " Lyon ");
        episodes[8] = new Episode(" The cliché East meets West rings true in Istanbul as Bourdain explores its confluence of food, culture and politics, featuring a Turkish breakfast with old friend Esra, an oil wrestling tournament, and lunch at an Armenian restaurant near the Golden Horn. Bourdain leaves the urban sprawl of Istanbul for Sedef Island and a meal with author and philosopher Gündüz Vassaf and celebrated Turkish actress Serra Yilmaz. ", seasons[5], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-7-6-1446969600-3713992816-large-400x225.jpg", 7, " Istanbul ");
        episodes[9] = new Episode(" After a 10 year absence, Bourdain abides by his promise to return, dining on chicken rendang for a reunion meal at Aunty Aini's, taking a boat ride to Kuching, traveling back to the longhouse at Entalau to attend the Gawai Rice festival, and acquiring a new hand-tapped tattoo, prefaced by a stop in street food paradise Kuala Lumpur for pork noodles and black pepper crab. ", seasons[5], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-6-6-1446361200-1689020116-large-400x225.jpg", 6, " Borneo ");
        episodes[10] = new Episode(" Acclaimed chef Marcus Samuelsson (Red Rooster, Aquavit) and his wife Maya take Bourdain on a personal tour of their native country to experience this nation beyond the headlines, first in Addis Adaba where they sample injera bread and beyaynetu platters, followed by drinking Turbo and eating Tibs with local skateboarding pioneers, listening to the traditional music of Azmari singers and legendary Ethiopian-jazz musician, Mahmoud Ahmed, a sampling Ethiopian coffee and a village feast with Maya's family in the Gurage region. ", seasons[5], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-5-6-1445756400-8067073645-large-400x225.jpg", 5, " Ethiopia ");
        episodes[11] = new Episode(" Bourdain visits the Bay Areas of San Francisco, Oakland and San Jose to take a personal journey  – in martial arts training with Brazilian Jiu Jitsu instructor Kurt Osiander, and healing through food, featuring dinner at the original Trader Vic's with author Sean Wilsey (Oh the Glory of it All) and at soul food restaurant Real Miss Ollie's with Bobby Seale (Black Panthers founding member). ", seasons[5], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-4-6-1445151600-2447802914-large-400x225.jpg", 4, " Bay Area ");
        episodes[12] = new Episode(" The alluring island of Okinawa, which endures tragic memories from World War II battles, is explored by Bourdain from historical, political, cultural and culinary perspectives. The tour includes a bloodless bullfight over a bowl of Yakisoba, a retrospective meal of Tundabun with the city's former governor, and a demonstration of open-hand karate experienced first-hand by Bourdain. ", seasons[5], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-3-6-1444546800-7345273224-large-400x225.jpg", 3, " Okinawa, Japan ");
        episodes[13] = new Episode(" Bourdain and his travel companion, chef Eric Ripert (Le Bernardin), visit France's oldest city to experience its stew of cultures and cuisines, indulging in chef Gerald Passedat's famous bouillabaisse, the classic pied et paquets, Algerian couscous and as much salumi and Corsican cheeses as they can handle. The pair also meet crime novelist Cedric Fabre, esteemed chef Georgiana Viou, and journalist Gilles Rof. ", seasons[5], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-2-6-1443942000-9331450364-large-400x225.jpg", 2, " Marseille, France ");
        episodes[14] = new Episode(" In the season six premiere, Bourdain explores Cuba – just as the half-century U.S. embargo softens and economic and social progress loom – from its bustling capital city Havana, to the slower paced, music mecca Santiago. Sampled food includes pig's head soup with plantains and pumpkin, flan in a beer can, and dogfish ceviche with pickled vegetables. The tour culminates with a dialogue-free tracking shot capturing the hopeful anxiety of its people, seemingly waiting for something to start. ", seasons[5], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-1-6-1443423600-9471253850-large-400x225.jpg", 1, " Cuba ");
        episodes[15] = new Episode(" An exclusive look at the new season of Anthony Bourdain: Parts Unknown. ", seasons[4], "http://static-api.guidebox.com/misc/episode/default_400x225.jpg", 10, " Prime Cuts S5 ");
        episodes[16] = new Episode("  The season five finale takes the host back to Beirut. Nicknamed The Paris of the Middle East, its nightlife is infamous, the population beautiful, and its cuisine legendary. During his travels, Bourdain meets up with freestyle artist Double A The Preecherman in the Mar Mikhael neighborhood, has a classic Lebanese meal with writer, publisher, activist Joumana Haddad, and visits a Syrian community in southern Beirut with CNN correspondent Nick Paton Walsh. ", seasons[4], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-8-5-1434870000-3378449897-large-400x225.jpg", 8, " Beirut ");
        episodes[17] = new Episode(" In this episode of Parts Unknown, Bourdain explores the other Hawaii, the one that those 8 million tourists don't see when they descend on the islands every year. Tony meets with travel writer and novelist Paul Theroux, Chef Andrew Le of Pig and the Lady in Honolulu, talent manager Shep Gordon and communes with residents of Molokai for a meal at an ancient oceanside fish pond. ", seasons[4], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-7-5-1434265200-7484760284-large-400x225.jpg", 7, " Hawaii ");
        episodes[18] = new Episode(" Drawing inspiration from iconic Hungarian born cinematographer Vilmos Zsigmond, Bourdain explores the beauty, culture, history, architecture and food of Budapest.  The culinary dishes sampled during his journey include goulash, fisherman's soup, blood sausage, stuffed cabbage and, during a stop at restaurant Pleh Csarda, a golden brown pancake heaped with chicken liver and bone marrow, fried schnitzel and venison stew. ", seasons[4], "http://static-api.guidebox.com/022615/thumbnails_episodes/15696-6-5-1433660400-3734520748-large-400x225.jpg", 6, " Budapest ");
        episodes[19] = new Episode(" Bourdain travels to his childhood home state with his brother Chris and rekindles memories at classic roadside joint Hiram's, known for its fried hotdogs, and Barnegat Light in Ocean County. He heads further down the shore to Atlantic City and stops by the Knife and Fork, Docks Oyster House with local reporter Brian Donohue, the Baltimore Grill to see husband and wife comedians Rich Vos and Bonnie McFarlane, and tours Asbury Park with none other than famed musician Southside Johnny. ", seasons[4], "http://static-api.guidebox.com/022615/thumbnails_episodes/15696-5-5-1433055600-3737991857-large-400x225.jpg", 5, " New Jersey ");
        episodes[20] = new Episode(" Unspoiled paradise or microcosm for the end of times? With acclaimed film director Darren Aronofsky (Noah, Requiem for a Dream, The Black Swan, Pi) as his travel companion, Bourdain explores this island nation off the southeastern coast of Africa.  Starting the journey in the chaotic, crowded capital city Tana, Bourdain samples the cuisine of legendary Malagasy chef Mariette Andrianjaka, including a goose specialty and and broth with chicken and ginger. ", seasons[4], "http://static-api.guidebox.com/022615/thumbnails_episodes/15696-4-5-1431846000-9244954637-large-400x225.jpg", 4, " Madagascar ");
        episodes[21] = new Episode(" Bourdain visits one of his favorite cities in Europe, Glasgow.  He makes his first stop at the Old College Bar for a pint, learns knife defense techniques from instructor Mark Davies, and tests his physical endurance while stalking red stag with writer A.A. Gill in the Scottish Highlands. Along the way Bourdain indulges in some surprising Scottish fare including deep-fried haggis, roasted grouse with bread sauce, and fresh venison. ", seasons[4], "http://static-api.guidebox.com/060515/thumbnails_episodes/15696-3-5-1431241200-8306704024-large-400x225.jpg", 3, " Scotland ");
        episodes[22] = new Episode(" Curiosity pays unexpected dividends, observes Iggy Pop, legendary rock musician, Miami resident and one of Bourdain's local guides in this multi-faceted, seductive city. The host visits favorite haunt Club Deuce bar, the B&M market in Little Haiti for cow foot soup, Islas Canarias with chef Michelle Bernstein for a different take on the Cuban sandwich, and explores The Miami Sound with Questlove and Willie Clark (founder, Deep City Records). ", seasons[4], "http://static-api.guidebox.com/022615/thumbnails_episodes/15696-2-5-1430636400-3765641879-large-400x225.jpg", 2, " Miami ");
        episodes[23] = new Episode(" The season premiere of Parts Unknown uses reverse chronology to tell the story of the host's return trip to South Korea after a 10-year absence. Bourdain experiences the nuances of hyper-modern Seoul which has its sights set on becoming the world's top exporter of popular culture. Food options include Korean fried chicken, and a vintage Korean army stew, budae jjigae, with Spam, canned baked beans, frankfurters, ramen noodles and Kimchi. ", seasons[4], "http://static-api.guidebox.com/022615/thumbnails_episodes/15696-1-5-1430031600-5519725634-large-400x225.jpg", 1, " Korea ");
        episodes[24] = new Episode(" Anthony Bourdain travels to Jamaica, known for Caribbean delicacies and feel-good vibes. He explores life in Port Antonio and Winnifred Beach, visits the home of James Bond author Ian Fleming and learns about music legend Bob Marley. ", seasons[3], "http://static-api.guidebox.com/091414/thumbnails_episodes/15696-8-4-1416124800-6147944634-large-400x225.jpg", 8, " Jamaica ");
        episodes[25] = new Episode(" Bourdain takes a trip to the haunts of his youth that marked the start of his culinary career, and he candidly discusses his descent into heroin addiction and recovery. He then heads to the western part of the state. ", seasons[3], "http://static-api.guidebox.com/091414/thumbnails_episodes/15696-7-4-1415520000-7238156702-large-400x225.jpg", 7, " Massachusetts ");
        episodes[26] = new Episode(" A trip to Iran exploring Tehran and Isfahan, and sites that include Imam Square, the Borje Milad. Guides for this tour include Washington Post reporter Jason Rezaian and his wife Yeganeh Salehi, who were subsequently detained by the Iranian government. ", seasons[3], "http://static-api.guidebox.com/091414/thumbnails_episodes/15696-8-4-1414911600-5776633248-large-400x225.jpg", 6, " Iran ");
        episodes[27] = new Episode(" Bourdain travels to Tanzania. He visits Zanzibar, a one-time slave trade hub, and enjoys the island's famous foods. On an excursion to the Serengeti and Ngorongoro Crater, Bourdain comes face to face with lions, elephants, and the great migration. ", seasons[3], "http://static-api.guidebox.com/091414/thumbnails_episodes/15696-5-4-1414306800-5700207469-large-400x225.jpg", 5, " Tanzania ");
        episodes[28] = new Episode(" Vietnam, the host's first love. A look at the city of Hue, excursions to the Dong Ba market, Vinh Moc tunnels, the Duyen Anh restaurant, and the Citadel. Sampled dishes include Com Hen, Bun Bo Hue and a special bird's nest soup. ", seasons[3], "http://static-api.guidebox.com/091414/thumbnails_episodes/15696-4-4-1413702000-3364269510-large-400x225.jpg", 4, " Vietnam ");
        episodes[29] = new Episode(" Parts Unknown travels to the host's first love, with a look at Hue, a city in central Vietnam, including excursions to the Dong Ba market, Vinh Moc tunnels, the Duyen Anh restaurant, and the Citadel.  Sampled dishes include Com Hen, Bun Bo Hue and a special bird's nest soup. ", seasons[3], "http://static-api.guidebox.com/091414/thumbnails_episodes/15696-3-4-0-3553146739-large-400x225.jpg", 3, " Paraguay ");
        episodes[30] = new Episode(" Bourdain explores the widely diverse cuisines and cultures found in the NYC borough just north of Manhattan. Bronx mainstays Afrika Bambaataa, Mellle Mel, and Baron Ambrosia help guide the host through the music, food, art, and other offerings of this often misunderstood part of the city. ", seasons[3], "http://static-api.guidebox.com/091414/thumbnails_episodes/15696-2-4-1412492400-9083910314-large-400x225.jpg", 2, " The Bronx ");
        episodes[31] = new Episode(" Anthony Bourdain explores Shanghai by savoring classic, home-style cuisine at restaurants that include Chun and Fuchun Xiaolong, and converses with locals who give their take on their country's booming economy and expanding global influence. ", seasons[3], "http://static-api.guidebox.com/091414/thumbnails_episodes/15696-1-4-1411887600-4361779327-large-400x225.jpg", 1, " Shanghai, China ");
        episodes[32] = new Episode(" Parts Unknown tours Bahia, known as the African heart of Brazil and internationally recognized for its Afro-Brazilian music, art, design and food. A look at the dance/martial art of Capoeira, the region's legendary food vendors, Salvadoran fishing neighborhoods, and a BBQ on the beach are featured. ", seasons[2], "http://static-api.guidebox.com/041014/thumbnails_episodes/15696-8-3-1402210800-1737668924-large-400x225.jpg", 8, " Brazil ");
        episodes[33] = new Episode(" Bourdain and his crew head to the Chiang Mai province of Northern Thailand along with celebrated chef and Thai food specialist Andy Ricker (Pok Pok restaurants) to explore the country's distinctive eating and drinking scene that varies by region and season. ", seasons[2], "http://static-api.guidebox.com/041014/thumbnails_episodes/15696-7-3-1401606000-5346590746-large-400x225.jpg", 7, " Thailand ");
        episodes[34] = new Episode(" Bourdain goes off the beaten path and explores some of the food and history of Mississippi including downtown Jackson's Big Apple Inn, known for its Pig Ear Sandwich and as a Civil Rights Era gathering place, and then travels into the Mississippi Delta to Po' Monkey's Social Club, a juke joint located in an old sharecropper structure. ", seasons[2], "http://static-api.guidebox.com/thumbs03_14/thumbnails_episodes/15696-6-3-1400396400-5277370377-large-400x225.jpg", 6, " Mississippi ");
        episodes[35] = new Episode(" On the eve of the Olympic games in Sochi, Bourdain takes his first trip in nearly 10 years to Russia, accompanied by his longtime traveling partner Zamir Gotta. Looking through the lens of a now Putin-controlled Russia, Bourdain confers with prominent locals, visits Moscow's historic Metropol Hotel, takes the Grand Express train to St. Petersburg, and explores the drinking and dining scene. ", seasons[2], "http://static-api.guidebox.com/thumbs03_14/thumbnails_episodes/15696-5-3-1399791600-8792589516-large-400x225.jpg", 5, " Russia ");
        episodes[36] = new Episode(" Bourdain travels to Mexico City, Oaxaca, and Cuernavaca to commune with local residents who express their passion through food, art, and the struggle for an improved quality of life. Addressing the latter issue, Bourdain talks with journalist Anabel Hernandez on the impact of the area's drug trade-related violence. ", seasons[2], "http://static-api.guidebox.com/thumbs03_14/thumbnails_episodes/15696-4-3-1399186800-3268889422-large-400x225.jpg", 4, " Mexico ");
        episodes[37] = new Episode(" In this food-centric episode, Bourdain accompanies world-renowned chef/restaurateur Daniel Boulud as they travel back to Boulud's hometown of Lyon, France for a once-in-a-lifetime pilgrimage to the city's rich food culture and legendary chefs, with a focus on Nouvelle Cuisine innovator Paul Bocuse. ", seasons[2], "http://static-api.guidebox.com/thumbs03_14/thumbnails_episodes/15696-3-3-1398582000-4422966810-large-400x225.jpg", 3, " Lyon ");
        episodes[38] = new Episode(" Bourdain travels to Las Vegas, a city known for over-indulgence, with food author Michael Ruhlman and visits locales that include Huntridge Tavern (in the shadow of the strip), and famed restaurant ? by Jose Andres. Also featured in the episode are Penn Jillette, and former mayor Oscar Goodman. ", seasons[2], "http://static-api.guidebox.com/thumbs03_14/thumbnails_episodes/15696-2-3-1397977200-4791373666-large-400x225.jpg", 2, " Las Vegas ");
        episodes[39] = new Episode(" In the Season 3 premiere of Anthony Bourdain Parts Unknown, Tony explores Punjab -- one of the most beautiful and relatively unknown areas of India. Punjab is the Sikh Holy Land and is also India's agricultural breadbasket. ", seasons[2], "http://static-api.guidebox.com/thumbs03_14/thumbnails_episodes/15696-1-3-1397372400-1010416160-large-400x225.jpg", 1, " Punjab, India ");
        episodes[40] = new Episode(" Few cities have experienced such a dramatic economic rise and fall of Detroit. In this episode of Parts Unknown, Bourdain explores the past, present and future of the Motor City. He steps into the lives of Detroit natives and sees the glory days of the past at the famed Packard Plant, the current state of the city's urban decay, and the promise of the future in the citizens who are rebuilding their communities. ", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-8-2-1384070400-9384480598-large-400x225.jpg", 8, " Detroit ");
        episodes[41] = new Episode(" Japan is a paradox.  The low birthrate, the dedication, the conformity, and the life of a salary man are well known. There is also a competitive and rigid culture that gives way to some unique subcultures.  Bourdain has traveled to Tokyo countless times, but on this trip he is in search of the city's dark, extreme, and bizarrely fetishistic underside. ", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-7-2-1383462000-9810401168-large-400x225.jpg", 7, " Tokyo ");
        episodes[42] = new Episode(" Once considered the most dangerous city in the world, Johannesburg now barely makes the top 50. But the end of the apartheid has led to vast changes in the city.  In this episode, Bourdain visits the suburb of Hillbrow (which remains a dangerous locale), spends a day in the life of a taxi driver and discovers the culture and food that make up modern day Johannesburg. ", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-6-2-1382252400-5398408328-large-400x225.jpg", 6, " South Africa ");
        episodes[43] = new Episode(" Parts Unknown explores the Sicilian way of life, which puts a premium on savoring family, life, and food.  Bourdain travels in search of those foods as he eats his way around the island.  He makes his home base at the Villa Monaci, on the outskirts of Catania with his enthusiastic, fast-talking sidekicks who counter the otherwise relaxed tempo and epic food porn of this episode. ", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-5-2-1381647600-5310781505-large-400x225.jpg", 5, " Sicily ");
        episodes[44] = new Episode(" This episode explores the food and natural beauty of Copenhagen, the economic and cultural center of Denmark. Home to famed chef Rene Redzepi and his brainchild Noma – regarded by critics as one of the world's best restaurants – Parts Unknown delves into the city's cuisine and the new Nordic creativity that infuses Redzepi's work at Noma. ", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-4-2-1381042800-5088125952-large-400x225.jpg", 4, " Copenhagen ");
        episodes[45] = new Episode(" Parts Unknown takes a close look at the mash-up of cultures that comprise this uniquely American state by sampling its food – a combination of Spanish, Mediterranean, Mexican, Pueblo and even chuck-wagon influences. New Mexico is also a land of drugs, guns, monster vehicles, and possibly extraterrestrials. It may also be the perfect place to investigate the underside of the Western cowboy ideal. ", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-3-2-1380438000-5576674333-large-400x225.jpg", 3, " New Mexico ");
        episodes[46] = new Episode(" Anthony Bourdain Parts Unknown explores Andalucía during Semana Santa (Holy Week, leading up to Easter), a time filled with great pageantry and excitement. Featured in this episode is Bourdain's longtime Director of Photography Zach Zamboni, who lives part-time in Granada and shows the host sights off the beaten path. ", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-2-2-1379833200-9373976178-large-400x225.jpg", 2, " Spain ");
        episodes[47] = new Episode(" In the season premiere of Anthony Bourdain Parts Unknown, the host and crew make their first trip to Israel, the West Bank and Gaza. While the political situation is often tense between the people living in these areas, Bourdain concentrates on their rich history, food and culture, and spends time with local chefs, home cooks, writers and amateur foodies. ", seasons[1], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-1-2-1379228400-5474856924-large-400x225.jpg", 1, " Jerusalem ");
        episodes[48] = new Episode(" Bourdain looks at the Congo as one of the more industrialized powers in Africa now largely crumbled to nothingness and chaos with Tim Butcher author of Blood River. ", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-8-1-1370761200-1054908778-large-400x225.jpg", 8, " Congo ");
        episodes[49] = new Episode(" Tony and his friend, world-renowned chef Eric Ripert, explore the far reaches of indigenous Andes in search of a rare variety of wild cocoa that is said to be the best in the world. They move from hip, modern Lima back in time into pre-Colombian Peru. ", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-7-1-1370156400-7329924716-large-400x225.jpg", 7, " Peru ");
        episodes[50] = new Episode(" Libyan hip-hop, Italian restaurants, tribal allegiances and post-war uncertainty in Libya.  Bourdain looks at the country through personal stories, food--and the music of anti-Qaddafi rapper expats who returned to fight. ", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-6-1-1368946800-1269055219-large-400x225.jpg", 6, " Libya ");
        episodes[51] = new Episode(" What Burroughs called Interzone, where artists like Burroughs, Bowles, Rimbaud, Verlaine, the Rolling Stones sought escape from Western moral prohibitions and the possibilities of great empty spaces. But what is it like now? ", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-5-1-1368342000-9460360165-large-400x225.jpg", 5, " Morocco (Tangier) ");
        episodes[52] = new Episode(" The two funniest and most brilliant chef/restaurateurs in Canada, Joe Beef's Dave McMillan and Fred Morin, take us across Canada by rail. ", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-4-1-1367737200-5573629285-large-400x225.jpg", 4, " Canada ");
        episodes[53] = new Episode(" The public face of Colombia has changed immensely over the past ten years and is still changing for the better.  Tony will explore several regions of the country from the mountains down to the Caribbean coast to the coca leaf growing inlands formerly controlled by drug cartels. ", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-3-1-1367132400-1727314266-large-400x225.jpg", 3, " Colombia ");
        episodes[54] = new Episode(" Roy Choi created a Brave New World of gastronomy almost single handedly with his LA based Kogi trucks. A Korean American who grew up on the fringes of Mexican and hip hop culture; his food reflects a new American idea of natural fusion--culinary influences that grew up next to and with each other. Bourdain examines the meeting point of Asian, Mexican, Latino culture in modern LA. ", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-2-1-1366527600-130323866-large-400x225.jpg", 2, " Los Angeles ");
        episodes[55] = new Episode(" With the slight relaxation of control by the government of Myanmar, Tony is finally able to explore one of the most fabled and beautiful areas of Asia. ", seasons[0], "http://static-api.guidebox.com/new_thumbs/thumbnails_episodes/15696-1-1-1365922800-6754041854-large-400x225.jpg", 1, " Myanmar ");
        episodeRepository.save(Arrays.asList(episodes));
    }


}
